
version: '3.8'

services:
  ml-processor:
    build:
      context: ./services/ml-processor
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  news-sender:
    build:
      context: ./services/news-sender
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  news-parser:
    build:
      context: ./services/news-parser
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  telegram-bot:
    build:
      context: ./services/telegram-bot
      dockerfile: Dockerfile
    ports:
      - "8084:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
