
version: '3.8'

services:
  ml-processor:
    image: $WERF_ML_PROCESSOR_DOCKER_IMAGE_NAME
    ports:
      - "8081:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  news-sender:
    image: $WERF_NEWS_PARSER_DOCKER_IMAGE_NAME
    ports:
      - "8082:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  news-parser:
    image: $WERF_NEWS_SENDER_DOCKER_IMAGE_NAME
    ports:
      - "8083:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

  telegram-bot:
    image: $WERF_TELEGRAM_BOT_DOCKER_IMAGE_NAME
    ports:
      - "8084:8080"
    command: uvicorn endpoints.main:app --host 0.0.0.0 --port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
