openapi: 3.0.0
info:
  description: Сервис для взаимодействия со всеми ML моделями
  title: ml-processor
  version: 1.0.0
servers:
- url: /
paths:
  /ml-processor/new_news:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_ml_processor_new_news_post_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_ml_processor_new_news_post_200_response'
          description: Успешный возврат записи в бд
      summary: Возвращает результат работы моделей
components:
  schemas:
    _ml_processor_new_news_post_request:
      properties:
        text:
          description: Текст новости
          example: "Поколение пепси поразило мир, успешно распознав текст на банке\
            \ шпротов"
          title: text
          type: string
      required:
      - text
      title: _ml_processor_new_news_post_request
      type: object
    _ml_processor_new_news_post_200_response:
      example:
        classes: "экономика, финансы"
        id: 42
        text: Поколение пепси распознало текст на банке шпротов
        embedding: "W0.12, 0.45, 0.78, ..., 0.99]"
      properties:
        id:
          description: Уникальный идентификатор новости в БД
          example: 42
          format: int64
          title: id
          type: integer
        text:
          description: Сокращенный текст новости
          example: Поколение пепси распознало текст на банке шпротов
          title: text
          type: string
        embedding:
          description: Векторное представление новости в виде строки (base64/json)
          example: "W0.12, 0.45, 0.78, ..., 0.99]"
          title: embedding
          type: string
        classes:
          description: Определенные классы/категории новости
          example: "экономика, финансы"
          title: classes
          type: string
      required:
      - classes
      - embedding
      - id
      - text
      title: _ml_processor_new_news_post_200_response
      type: object
