openapi: 3.0.0
info:
  description: Сервис для взаимодействия со всеми ML моделями
  title: ml-processor
  version: 1.0.0
servers:
- url: /
paths:
  /ml-processor/ping:
    get:
      operationId: getGreeting
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGreeting_200_response'
          description: Successful response
      summary: Returns a greeting and the current time
components:
  schemas:
    getGreeting_200_response:
      example:
        currentTime: 2023-10-10T14:48:00Z
        message: "Hello, World!"
        ml_specific_thing: 0
      properties:
        message:
          example: "Hello, World!"
          title: message
          type: string
        currentTime:
          example: 2023-10-10T14:48:00Z
          format: date-time
          title: currentTime
          type: string
        ml_specific_thing:
          title: ml_specific_thing
          type: integer
      title: getGreeting_200_response
      type: object
