openapi: 3.0.0
info:
  contact:
    email: we_dont_care@kys.com
    name: API Support
    url: https://rt.pornhub.com/
  description: A simple service that returns a greeting and current time.
  title: example-service-skeleton
  version: 1.0.0
servers:
- url: /
paths:
  /greet:
    get:
      operationId: getGreeting
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/getGreeting_200_response'
          description: Successful response
      summary: Returns a greeting and the current time
      tags:
      - Greeting
components:
  schemas:
    getGreeting_200_response:
      example:
        currentTime: 2023-10-10T14:48:00Z
        message: "Hello, World!"
      properties:
        message:
          example: "Hello, World!"
          title: message
          type: string
        currentTime:
          example: 2023-10-10T14:48:00Z
          format: date-time
          title: currentTime
          type: string
      title: getGreeting_200_response
      type: object
