
openapi: 3.0.0
info:
  version: 1.0.0
  title: example-service-skeleton
  description: A simple service that returns a greeting and current time.
  contact:
    name: API Support
    url: https://rt.pornhub.com/
    email: we_dont_care@kys.com
paths:
  /greet:
    get:
      summary: Returns a greeting and the current time
      operationId: getGreeting
      tags:
        - Greeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
                  currentTime:
                    type: string
                    format: date-time
                    example: 2023-10-10T14:48:00.000Z
