openapi: 3.0.0
info:
  version: 1.0.0
  title: telegram-bot
  description: Сервис для взаимодействия с телеграммом
paths:
  /telegram-bot/ping:
    get:
      summary: Returns a greeting and the current time
      operationId: getGreeting
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
                  currentTime:
                    type: string
                    format: date-time
                    example: 2023-10-10T14:48:00.000Z
                  tg_bot_thing:
                    type: object
                    properties:
                      test_prop:
                        type: string