apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-processor-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-processor-backend
  template:
    metadata:
      labels:
        app: ml-processor-backend
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: ml-processor
        image: {{ .Values.werf.image.ml_processor }}
        ports:
        - containerPort: 8080
        env:
          - name: EXAMPLE_ENV
            value: "example_value"