apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-sender-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-sender-backend
  template:
    metadata:
      labels:
        app: news-sender-backend
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: news-sender
        image: {{ .Values.werf.image.news_sender }}
        ports:
        - containerPort: 8080
        env:
          - name: EXAMPLE_ENV
            value: "example_value"