apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegram-bot-backend
  template:
    metadata:
      labels:
        app: telegram-bot-backend
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: app-backend
        image: {{ .Values.werf.image.telegram-bot }}
        ports:
        - containerPort: 8080
        env:
          - name: EXAMPLE_ENV
            value: "example_value"