name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install werf
        uses: werf/actions/install@v2
        
      - name: Run script
        run: |
          . $(werf ci-env github --as-file) 
          werf converge
        env:
          WERF_KUBECONFIG_BASE64: ${{ secrets.KUBE_CONFIG_BASE64_DATA }}
          WERF_ENV: production
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}