name: Production Deployment
on:
  push:
    branches: [main]
jobs:
  converge:
    name: Converge
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Install werf
        uses: werf/actions/install@v2
        
      - name: Run script
        run: |
          . $(werf ci-env github --as-file) 
          werf converge
        env:
          WERF_SET_ENV_URL: "envUrl=http://example.com"
          MONGO_HOST: ${{ secrets.MONGO_HOST }}
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
